# Generated by Django 4.0.6 on 2023-03-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('colors', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=200)),
                ('category', models.CharField(choices=[('1', 'Hair Toppers'), ('2', 'All Things Hair'), ('3', 'Strandouts')], max_length=200)),
            ],
        ),
    ]
