# Generated by Django 3.2 on 2023-03-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_banner_brand_cartorder_cartorderitems_category_color_product_productattribute_size_useraddressbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
    ]
