# Generated by Django 3.2 on 2023-03-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0005_auto_20230310_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderdetails',
            name='price',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cartorderdetails',
            name='qty',
            field=models.CharField(max_length=200),
        ),
    ]
